apiVersion: v1
kind: Service              # 1
metadata:
  name: s-b-d-lb
spec:
  type: LoadBalancer       # 2
  ports:
    - port: 8888               # 3
#      порт, по которому сервис принимает запросы.
      protocol: TCP          # 4
      targetPort: 8082         # 5
#      порт, на который перенаправляются входящие запросы.
  selector:                # 6
    app: s-b-d             # 7
#    это свойство указывает на то, с какими подами будет работать сервис.
#    А именно — это поды, которым назначена метка app: s-b-d

#  kubectl create -f spring-boot-docker-lb.yml