apiVersion: v1
kind: Pod                                            # 1
metadata:
  name: s-b-d-1                                      # 2
  labels:
    app: s-b-d
spec:                                                # 3
  containers:
    - image: serzhzag/spring-boot-docker            # 4
      name: s-b-d                                    # 5
      imagePullPolicy: IfNotPresent
#      imagePullPolicy: Never
      ports:
#        - containerPort: 80
        - containerPort: 8082

#  kubectl create -f spring-boot-docker.yml
#  kubectl get pods
#  kubectl describe pod s-b-d